const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("mimoInput", {
  getStatus: () => ipcRenderer.invoke("app:status"),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (settings) => ipcRenderer.invoke("settings:save", settings),
  checkHotkey: (payload) => ipcRenderer.invoke("shortcut:check", payload),
  startHotkeyCapture: () => ipcRenderer.invoke("shortcut:capture-start"),
  endHotkeyCapture: () => ipcRenderer.invoke("shortcut:capture-end"),
  log: (message, detail) => ipcRenderer.invoke("app:log", message, detail),
  transcribe: (payload) => ipcRenderer.invoke("voice:transcribe", payload),
  transcribeSegment: (payload) => ipcRenderer.invoke("voice:segment:transcribe", payload),
  cleanText: (payload) => ipcRenderer.invoke("voice:clean-text", payload),
  startRealtimeAsr: () => ipcRenderer.invoke("voice:realtime:start"),
  appendRealtimeAudio: (base64Audio) => ipcRenderer.invoke("voice:realtime:append", base64Audio),
  finishRealtimeAsr: (payload) => ipcRenderer.invoke("voice:realtime:finish", payload),
  cancelRealtimeAsr: () => ipcRenderer.invoke("voice:realtime:cancel"),
  testConnection: () => ipcRenderer.invoke("connection:test"),
  injectText: (text) => ipcRenderer.invoke("input:inject", text),
  copyText: (text) => ipcRenderer.invoke("clipboard:write-text", text),
  hide: () => ipcRenderer.invoke("window:hide"),
  clearRecordingKeys: () => ipcRenderer.invoke("recording:keys:clear"),
  resizeRecordingWindow: (size) => ipcRenderer.invoke("window:recording-resize", size),
  setCompactMode: (isCompact) => ipcRenderer.invoke("window:compact", isCompact),
  minimizeWindow: () => ipcRenderer.invoke("window:minimize"),
  toggleMaximizeWindow: () => ipcRenderer.invoke("window:toggle-maximize"),
  isWindowMaximized: () => ipcRenderer.invoke("window:is-maximized"),
  onWindowMaximized: (callback) => ipcRenderer.on("window-maximized", (_event, maximized) => callback(Boolean(maximized))),
  openSettings: () => ipcRenderer.invoke("window:settings"),
  openResultWindow: () => ipcRenderer.invoke("window:result"),
  openMeetingWorkspace: () => ipcRenderer.invoke("window:meeting"),
  openFileWorkspace: () => ipcRenderer.invoke("window:file"),
  onHotkeyRecord: (callback) => ipcRenderer.on("hotkey-record", callback),
  onRecordingCommand: (callback) => ipcRenderer.on("recording-command", (_event, command) => callback(command)),
  onRetryLastVoiceRequest: (callback) => ipcRenderer.on("retry-last-voice-request", callback),
  onOpenSettings: (callback) => ipcRenderer.on("open-settings", callback),
  onOpenMeeting: (callback) => ipcRenderer.on("open-meeting", callback),
  onOpenFile: (callback) => ipcRenderer.on("open-file", callback),
  onWindowMode: (callback) => ipcRenderer.on("window-mode", (_event, mode) => callback(mode)),
  onWindowBlur: (callback) => ipcRenderer.on("window-blur", callback),
  onPartialTranscript: (callback) => ipcRenderer.on("voice:partial-transcript", (_event, text) => callback(text)),
  // Stage 0B/2B/4A meeting API — isolated from voice recording IPC.
  // Whitelist only: sessionId, deviceId, systemDeviceId, captureMode, title, resetAttempts,
  // mode/processMode, bitrateKbps, forceResubmit (Stage 4C). No absolute paths/secrets.
  // No absolute paths. transcript:get returns text by design; status/list never include it.
  meetingStatus: () => ipcRenderer.invoke("meeting:status"),
  meetingListSessions: (payload) => ipcRenderer.invoke("meeting:sessions:list", payload),
  meetingScanSession: (sessionId) => ipcRenderer.invoke("meeting:sessions:scan", sessionId),
  meetingHelperReady: () => ipcRenderer.invoke("meeting:helper:ready"),
  meetingCreateSession: (payload) => ipcRenderer.invoke("meeting:session:create", payload),
  meetingStart: (payload) => ipcRenderer.invoke("meeting:capture:start", payload),
  meetingPause: (payload) => ipcRenderer.invoke("meeting:capture:pause", payload),
  meetingResume: (payload) => ipcRenderer.invoke("meeting:capture:resume", payload),
  meetingStop: (payload) => ipcRenderer.invoke("meeting:capture:stop", payload),
  meetingQueryDevices: () => ipcRenderer.invoke("meeting:devices:query"),
  meetingProcessStart: (payload) => ipcRenderer.invoke("meeting:process:start", payload),
  meetingProcessStatus: (payload) => ipcRenderer.invoke("meeting:process:status", payload),
  meetingProcessRetry: (payload) => ipcRenderer.invoke("meeting:process:retry", payload),
  meetingProcessCancel: (payload) => ipcRenderer.invoke("meeting:process:cancel", payload),
  meetingEnhancedTest: (payload) => ipcRenderer.invoke("meeting:enhanced:test", payload),
  meetingTranscriptGet: (payload) => ipcRenderer.invoke("meeting:transcript:get", payload),
  // Stage 3A analysis — status/list never include bodies; corrected/summary endpoints do by design
  meetingAnalysisStart: (payload) => ipcRenderer.invoke("meeting:analysis:start", payload),
  meetingAnalysisStatus: (payload) => ipcRenderer.invoke("meeting:analysis:status", payload),
  meetingAnalysisRetry: (payload) => ipcRenderer.invoke("meeting:analysis:retry", payload),
  meetingAnalysisCancel: (payload) => ipcRenderer.invoke("meeting:analysis:cancel", payload),
  meetingAnalysisCorrected: (payload) => ipcRenderer.invoke("meeting:analysis:corrected", payload),
  meetingAnalysisSummary: (payload) => ipcRenderer.invoke("meeting:analysis:summary", payload),
  // Stage 4B-core
  meetingRenameSession: (payload) => ipcRenderer.invoke("meeting:session:rename", payload),
  meetingSpeakerMapGet: (payload) => ipcRenderer.invoke("meeting:speaker-map:get", payload),
  meetingSpeakerMapSet: (payload) => ipcRenderer.invoke("meeting:speaker-map:set", payload),
  meetingExportSave: (payload) => ipcRenderer.invoke("meeting:export:save", payload),
  fileExportSave: (payload) => ipcRenderer.invoke("file:export:save", payload),
  meetingImportWav: (payload) => ipcRenderer.invoke("meeting:import:wav", payload),
  meetingImportMedia: (payload) => ipcRenderer.invoke("meeting:import:media", payload),
  meetingImportStatus: (payload) => ipcRenderer.invoke("meeting:import:status", payload),
  meetingImportCancel: (payload) => ipcRenderer.invoke("meeting:import:cancel", payload),
  meetingPlaybackToken: (payload) => ipcRenderer.invoke("meeting:playback:token", payload)
});
